Repository Duit-Foundation/flutter_duit, pull requests merged in 2025-02, with the labels that each got.

#166 feat: SafeArea widget
  lib/src/attributes/index.dart
  lib/src/attributes/safe_area_attributes.dart
  lib/src/ui/models/element.dart
  lib/src/ui/models/element_models.dart
  lib/src/ui/models/element_type.dart
  lib/src/ui/widgets/index.dart
  lib/src/ui/widgets/safe_area.dart
  lib/src/ui/widgets/widget_fabric.dart
  lib/src/utils/attribute_parser.dart
  test/d_safe_area_test.dart
Labels: feature

#164 feat: RemoteSubtree widget
  lib/src/attributes/index.dart
  lib/src/attributes/remote_subtree_attributes.dart
  lib/src/duit_impl/subtree_holder.dart
  lib/src/ui/models/element.dart
  lib/src/ui/models/element_models.dart
  lib/src/ui/models/element_type.dart
  lib/src/ui/models/type_def.dart
  lib/src/ui/widgets/index.dart
  lib/src/ui/widgets/remote_subtree.dart
  lib/src/ui/widgets/subtree.dart
  lib/src/ui/widgets/widget_fabric.dart
  lib/src/utils/attribute_parser.dart
  test/d_remote_test.dart
  test/utils.dart
Labels: feature

#167 patch: Custom widget controller auto-typecast
  example/lib/main.dart
  example/lib/src/custom/example/factories.dart
  example/lib/src/custom/example/model.dart
  lib/src/ui/models/element_models.dart
Labels: Improvement

#168 patch: Rebinding the controller after type casting
  .github/workflows/duit_pr.yaml
  lib/src/controller/view_controller.dart
  test/d_component_test.dart
  test/d_custom_test.dart
  test/d_listview_test.dart
  test/mocks/custom.dart
Labels: bug

#186 feat: IntrinsicWidth widget(#76)
  lib/src/attributes/index.dart
  lib/src/attributes/intrinsic_width_attributes.dart
  lib/src/ui/models/element.dart
  lib/src/ui/models/element_models.dart
  lib/src/ui/models/element_type.dart
  lib/src/ui/widgets/index.dart
  lib/src/ui/widgets/intrinsic_width.dart
  lib/src/ui/widgets/widget_fabric.dart
  lib/src/utils/attribute_parser.dart
  test/d_intrinsic_width_test.dart
Labels: feature

#190 patch: Export kernel API
  example/lib/main.dart
  example/lib/src/theme/custom_token.dart
  example/lib/src/theme/loader.dart
  example/lib/src/theme/override_token.dart
  lib/src/kernel_api/index.dart
  lib/src/view_manager/simple_manager.dart
Labels: Improvement
